//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace VisualPacker.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool PreferenceWindowWeightRestrictionCheckBoxEnabled {
            get {
                return ((bool)(this["PreferenceWindowWeightRestrictionCheckBoxEnabled"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("2015-04-01")]
        public DateTime PreferenceWindow_FirstDateOfWeightRestriction {
            get {
                return ((DateTime)(this["PreferenceWindow_FirstDateOfWeightRestriction"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("2015-05-31")]
        public DateTime PreferenceWindow_LastDateOfWeightRestriction {
            get {
                return ((DateTime)(this["PreferenceWindow_LastDateOfWeightRestriction"]));
            }
        }
    }
}
